/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CustomerRouteRouteImport } from './routes/customer/route'
import { Route as FinanceRouteRouteImport } from './routes/finance/route'
import { Route as InventoryRouteRouteImport } from './routes/inventory/route'
import { Route as ManagementRouteRouteImport } from './routes/management/route'
import { Route as ManagerRouteRouteImport } from './routes/manager/route'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StaffRouteRouteImport } from './routes/staff/route'
import { Route as TechnicianRouteRouteImport } from './routes/technician/route'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicServicesRouteImport } from './routes/_public.services'
import { Route as PublicTrackRouteImport } from './routes/_public.track'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as CustomerIndexRouteImport } from './routes/customer/index'
import { Route as CustomerBookRouteImport } from './routes/customer/book'
import { Route as CustomerDashboardRouteImport } from './routes/customer/dashboard'
import { Route as CustomerRepairsRouteImport } from './routes/customer/repairs'
import { Route as FinanceIndexRouteImport } from './routes/finance/index'
import { Route as FinanceBillingRouteImport } from './routes/finance/billing'
import { Route as FinancePnlRouteImport } from './routes/finance/pnl'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as InventoryDashboardRouteImport } from './routes/inventory/dashboard'
import { Route as InventorySuppliersRouteImport } from './routes/inventory/suppliers'
import { Route as ManagementIndexRouteImport } from './routes/management/index'
import { Route as ManagementDashboardRouteImport } from './routes/management/dashboard'
import { Route as ManagerIndexRouteImport } from './routes/manager/index'
import { Route as ManagerApprovalsRouteImport } from './routes/manager/approvals'
import { Route as ManagerReportsRouteImport } from './routes/manager/reports'
import { Route as StaffCustomersRouteImport } from './routes/staff/customers'
import { Route as StaffRepairsRouteImport } from './routes/staff/repairs'
import { Route as TechnicianIndexRouteImport } from './routes/technician/index'
import { Route as TechnicianDashboardRouteImport } from './routes/technician/dashboard'
import { Route as TechnicianJobsRouteImport } from './routes/technician/jobs'
import { Route as PublicInvoiceIdRouteImport } from './routes/_public.invoice.$id'
import { Route as ApiWebhooksWhatsappRouteImport } from './routes/api.webhooks.whatsapp'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRouteRoute = CustomerRouteRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRouteRoute = FinanceRouteRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRouteRoute = InventoryRouteRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementRouteRoute = ManagementRouteRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRouteRoute = ManagerRouteRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRouteRoute = StaffRouteRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianRouteRoute = TechnicianRouteRouteImport.update({
  id: '/technician',
  path: '/technician',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicServicesRoute = PublicServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTrackRoute = PublicTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => PublicRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerBookRoute = CustomerBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerRepairsRoute = CustomerRepairsRouteImport.update({
  id: '/repairs',
  path: '/repairs',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRouteRoute,
} as any)
const FinanceBillingRoute = FinanceBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => FinanceRouteRoute,
} as any)
const FinancePnlRoute = FinancePnlRouteImport.update({
  id: '/pnl',
  path: '/pnl',
  getParentRoute: () => FinanceRouteRoute,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventoryRouteRoute,
} as any)
const InventoryDashboardRoute = InventoryDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => InventoryRouteRoute,
} as any)
const InventorySuppliersRoute = InventorySuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => InventoryRouteRoute,
} as any)
const ManagementIndexRoute = ManagementIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagementRouteRoute,
} as any)
const ManagementDashboardRoute = ManagementDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ManagementRouteRoute,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerApprovalsRoute = ManagerApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerReportsRoute = ManagerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const StaffCustomersRoute = StaffCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffRepairsRoute = StaffRepairsRouteImport.update({
  id: '/repairs',
  path: '/repairs',
  getParentRoute: () => StaffRouteRoute,
} as any)
const TechnicianIndexRoute = TechnicianIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TechnicianRouteRoute,
} as any)
const TechnicianDashboardRoute = TechnicianDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TechnicianRouteRoute,
} as any)
const TechnicianJobsRoute = TechnicianJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => TechnicianRouteRoute,
} as any)
const PublicInvoiceIdRoute = PublicInvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => PublicRoute,
} as any)
const ApiWebhooksWhatsappRoute = ApiWebhooksWhatsappRouteImport.update({
  id: '/api/webhooks/whatsapp',
  path: '/api/webhooks/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/customer': typeof CustomerRouteRouteWithChildren
  '/finance': typeof FinanceRouteRouteWithChildren
  '/inventory': typeof InventoryRouteRouteWithChildren
  '/management': typeof ManagementRouteRouteWithChildren
  '/manager': typeof ManagerRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/technician': typeof TechnicianRouteRouteWithChildren
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/services': typeof PublicServicesRoute
  '/track': typeof PublicTrackRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/customer/book': typeof CustomerBookRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/repairs': typeof CustomerRepairsRoute
  '/finance/billing': typeof FinanceBillingRoute
  '/finance/pnl': typeof FinancePnlRoute
  '/inventory/dashboard': typeof InventoryDashboardRoute
  '/inventory/suppliers': typeof InventorySuppliersRoute
  '/management/dashboard': typeof ManagementDashboardRoute
  '/manager/approvals': typeof ManagerApprovalsRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/staff/customers': typeof StaffCustomersRoute
  '/staff/repairs': typeof StaffRepairsRoute
  '/technician/dashboard': typeof TechnicianDashboardRoute
  '/technician/jobs': typeof TechnicianJobsRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/management/': typeof ManagementIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/technician/': typeof TechnicianIndexRoute
  '/invoice/$id': typeof PublicInvoiceIdRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
}
export interface FileRoutesByTo {
  '/staff': typeof StaffRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/services': typeof PublicServicesRoute
  '/track': typeof PublicTrackRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/customer/book': typeof CustomerBookRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/repairs': typeof CustomerRepairsRoute
  '/finance/billing': typeof FinanceBillingRoute
  '/finance/pnl': typeof FinancePnlRoute
  '/inventory/dashboard': typeof InventoryDashboardRoute
  '/inventory/suppliers': typeof InventorySuppliersRoute
  '/management/dashboard': typeof ManagementDashboardRoute
  '/manager/approvals': typeof ManagerApprovalsRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/staff/customers': typeof StaffCustomersRoute
  '/staff/repairs': typeof StaffRepairsRoute
  '/technician/dashboard': typeof TechnicianDashboardRoute
  '/technician/jobs': typeof TechnicianJobsRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/customer': typeof CustomerIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/management': typeof ManagementIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/technician': typeof TechnicianIndexRoute
  '/invoice/$id': typeof PublicInvoiceIdRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteRouteWithChildren
  '/customer': typeof CustomerRouteRouteWithChildren
  '/finance': typeof FinanceRouteRouteWithChildren
  '/inventory': typeof InventoryRouteRouteWithChildren
  '/management': typeof ManagementRouteRouteWithChildren
  '/manager': typeof ManagerRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/technician': typeof TechnicianRouteRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/services': typeof PublicServicesRoute
  '/_public/track': typeof PublicTrackRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/customer/book': typeof CustomerBookRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/repairs': typeof CustomerRepairsRoute
  '/finance/billing': typeof FinanceBillingRoute
  '/finance/pnl': typeof FinancePnlRoute
  '/inventory/dashboard': typeof InventoryDashboardRoute
  '/inventory/suppliers': typeof InventorySuppliersRoute
  '/management/dashboard': typeof ManagementDashboardRoute
  '/manager/approvals': typeof ManagerApprovalsRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/staff/customers': typeof StaffCustomersRoute
  '/staff/repairs': typeof StaffRepairsRoute
  '/technician/dashboard': typeof TechnicianDashboardRoute
  '/technician/jobs': typeof TechnicianJobsRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/management/': typeof ManagementIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/technician/': typeof TechnicianIndexRoute
  '/_public/invoice/$id': typeof PublicInvoiceIdRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/customer'
    | '/finance'
    | '/inventory'
    | '/management'
    | '/manager'
    | '/staff'
    | '/technician'
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/about'
    | '/contact'
    | '/services'
    | '/track'
    | '/admin/settings'
    | '/customer/book'
    | '/customer/dashboard'
    | '/customer/repairs'
    | '/finance/billing'
    | '/finance/pnl'
    | '/inventory/dashboard'
    | '/inventory/suppliers'
    | '/management/dashboard'
    | '/manager/approvals'
    | '/manager/reports'
    | '/staff/customers'
    | '/staff/repairs'
    | '/technician/dashboard'
    | '/technician/jobs'
    | '/admin/'
    | '/customer/'
    | '/finance/'
    | '/inventory/'
    | '/management/'
    | '/manager/'
    | '/technician/'
    | '/invoice/$id'
    | '/api/webhooks/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/staff'
    | '/auth'
    | '/sitemap.xml'
    | '/about'
    | '/contact'
    | '/services'
    | '/track'
    | '/admin/settings'
    | '/customer/book'
    | '/customer/dashboard'
    | '/customer/repairs'
    | '/finance/billing'
    | '/finance/pnl'
    | '/inventory/dashboard'
    | '/inventory/suppliers'
    | '/management/dashboard'
    | '/manager/approvals'
    | '/manager/reports'
    | '/staff/customers'
    | '/staff/repairs'
    | '/technician/dashboard'
    | '/technician/jobs'
    | '/'
    | '/admin'
    | '/customer'
    | '/finance'
    | '/inventory'
    | '/management'
    | '/manager'
    | '/technician'
    | '/invoice/$id'
    | '/api/webhooks/whatsapp'
  id:
    | '__root__'
    | '/admin'
    | '/customer'
    | '/finance'
    | '/inventory'
    | '/management'
    | '/manager'
    | '/staff'
    | '/technician'
    | '/_public'
    | '/auth'
    | '/sitemap.xml'
    | '/_public/about'
    | '/_public/contact'
    | '/_public/services'
    | '/_public/track'
    | '/admin/settings'
    | '/customer/book'
    | '/customer/dashboard'
    | '/customer/repairs'
    | '/finance/billing'
    | '/finance/pnl'
    | '/inventory/dashboard'
    | '/inventory/suppliers'
    | '/management/dashboard'
    | '/manager/approvals'
    | '/manager/reports'
    | '/staff/customers'
    | '/staff/repairs'
    | '/technician/dashboard'
    | '/technician/jobs'
    | '/_public/'
    | '/admin/'
    | '/customer/'
    | '/finance/'
    | '/inventory/'
    | '/management/'
    | '/manager/'
    | '/technician/'
    | '/_public/invoice/$id'
    | '/api/webhooks/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CustomerRouteRoute: typeof CustomerRouteRouteWithChildren
  FinanceRouteRoute: typeof FinanceRouteRouteWithChildren
  InventoryRouteRoute: typeof InventoryRouteRouteWithChildren
  ManagementRouteRoute: typeof ManagementRouteRouteWithChildren
  ManagerRouteRoute: typeof ManagerRouteRouteWithChildren
  StaffRouteRoute: typeof StaffRouteRouteWithChildren
  TechnicianRouteRoute: typeof TechnicianRouteRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiWebhooksWhatsappRoute: typeof ApiWebhooksWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management': {
      id: '/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician': {
      id: '/technician'
      path: '/technician'
      fullPath: '/technician'
      preLoaderRoute: typeof TechnicianRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/services': {
      id: '/_public/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof PublicServicesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/track': {
      id: '/_public/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof PublicTrackRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/customer/book': {
      id: '/customer/book'
      path: '/book'
      fullPath: '/customer/book'
      preLoaderRoute: typeof CustomerBookRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/customer/dashboard': {
      id: '/customer/dashboard'
      path: '/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/customer/repairs': {
      id: '/customer/repairs'
      path: '/repairs'
      fullPath: '/customer/repairs'
      preLoaderRoute: typeof CustomerRepairsRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRouteRoute
    }
    '/finance/billing': {
      id: '/finance/billing'
      path: '/billing'
      fullPath: '/finance/billing'
      preLoaderRoute: typeof FinanceBillingRouteImport
      parentRoute: typeof FinanceRouteRoute
    }
    '/finance/pnl': {
      id: '/finance/pnl'
      path: '/pnl'
      fullPath: '/finance/pnl'
      preLoaderRoute: typeof FinancePnlRouteImport
      parentRoute: typeof FinanceRouteRoute
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof InventoryRouteRoute
    }
    '/inventory/dashboard': {
      id: '/inventory/dashboard'
      path: '/dashboard'
      fullPath: '/inventory/dashboard'
      preLoaderRoute: typeof InventoryDashboardRouteImport
      parentRoute: typeof InventoryRouteRoute
    }
    '/inventory/suppliers': {
      id: '/inventory/suppliers'
      path: '/suppliers'
      fullPath: '/inventory/suppliers'
      preLoaderRoute: typeof InventorySuppliersRouteImport
      parentRoute: typeof InventoryRouteRoute
    }
    '/management/': {
      id: '/management/'
      path: '/'
      fullPath: '/management/'
      preLoaderRoute: typeof ManagementIndexRouteImport
      parentRoute: typeof ManagementRouteRoute
    }
    '/management/dashboard': {
      id: '/management/dashboard'
      path: '/dashboard'
      fullPath: '/management/dashboard'
      preLoaderRoute: typeof ManagementDashboardRouteImport
      parentRoute: typeof ManagementRouteRoute
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/approvals': {
      id: '/manager/approvals'
      path: '/approvals'
      fullPath: '/manager/approvals'
      preLoaderRoute: typeof ManagerApprovalsRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/reports': {
      id: '/manager/reports'
      path: '/reports'
      fullPath: '/manager/reports'
      preLoaderRoute: typeof ManagerReportsRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/staff/customers': {
      id: '/staff/customers'
      path: '/customers'
      fullPath: '/staff/customers'
      preLoaderRoute: typeof StaffCustomersRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/repairs': {
      id: '/staff/repairs'
      path: '/repairs'
      fullPath: '/staff/repairs'
      preLoaderRoute: typeof StaffRepairsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/technician/': {
      id: '/technician/'
      path: '/'
      fullPath: '/technician/'
      preLoaderRoute: typeof TechnicianIndexRouteImport
      parentRoute: typeof TechnicianRouteRoute
    }
    '/technician/dashboard': {
      id: '/technician/dashboard'
      path: '/dashboard'
      fullPath: '/technician/dashboard'
      preLoaderRoute: typeof TechnicianDashboardRouteImport
      parentRoute: typeof TechnicianRouteRoute
    }
    '/technician/jobs': {
      id: '/technician/jobs'
      path: '/jobs'
      fullPath: '/technician/jobs'
      preLoaderRoute: typeof TechnicianJobsRouteImport
      parentRoute: typeof TechnicianRouteRoute
    }
    '/_public/invoice/$id': {
      id: '/_public/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/invoice/$id'
      preLoaderRoute: typeof PublicInvoiceIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/webhooks/whatsapp': {
      id: '/api/webhooks/whatsapp'
      path: '/api/webhooks/whatsapp'
      fullPath: '/api/webhooks/whatsapp'
      preLoaderRoute: typeof ApiWebhooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface CustomerRouteRouteChildren {
  CustomerBookRoute: typeof CustomerBookRoute
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  CustomerRepairsRoute: typeof CustomerRepairsRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
}

const CustomerRouteRouteChildren: CustomerRouteRouteChildren = {
  CustomerBookRoute: CustomerBookRoute,
  CustomerDashboardRoute: CustomerDashboardRoute,
  CustomerRepairsRoute: CustomerRepairsRoute,
  CustomerIndexRoute: CustomerIndexRoute,
}

const CustomerRouteRouteWithChildren = CustomerRouteRoute._addFileChildren(
  CustomerRouteRouteChildren,
)

interface FinanceRouteRouteChildren {
  FinanceBillingRoute: typeof FinanceBillingRoute
  FinancePnlRoute: typeof FinancePnlRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
}

const FinanceRouteRouteChildren: FinanceRouteRouteChildren = {
  FinanceBillingRoute: FinanceBillingRoute,
  FinancePnlRoute: FinancePnlRoute,
  FinanceIndexRoute: FinanceIndexRoute,
}

const FinanceRouteRouteWithChildren = FinanceRouteRoute._addFileChildren(
  FinanceRouteRouteChildren,
)

interface InventoryRouteRouteChildren {
  InventoryDashboardRoute: typeof InventoryDashboardRoute
  InventorySuppliersRoute: typeof InventorySuppliersRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

const InventoryRouteRouteChildren: InventoryRouteRouteChildren = {
  InventoryDashboardRoute: InventoryDashboardRoute,
  InventorySuppliersRoute: InventorySuppliersRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}

const InventoryRouteRouteWithChildren = InventoryRouteRoute._addFileChildren(
  InventoryRouteRouteChildren,
)

interface ManagementRouteRouteChildren {
  ManagementDashboardRoute: typeof ManagementDashboardRoute
  ManagementIndexRoute: typeof ManagementIndexRoute
}

const ManagementRouteRouteChildren: ManagementRouteRouteChildren = {
  ManagementDashboardRoute: ManagementDashboardRoute,
  ManagementIndexRoute: ManagementIndexRoute,
}

const ManagementRouteRouteWithChildren = ManagementRouteRoute._addFileChildren(
  ManagementRouteRouteChildren,
)

interface ManagerRouteRouteChildren {
  ManagerApprovalsRoute: typeof ManagerApprovalsRoute
  ManagerReportsRoute: typeof ManagerReportsRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteRouteChildren: ManagerRouteRouteChildren = {
  ManagerApprovalsRoute: ManagerApprovalsRoute,
  ManagerReportsRoute: ManagerReportsRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteRouteWithChildren = ManagerRouteRoute._addFileChildren(
  ManagerRouteRouteChildren,
)

interface StaffRouteRouteChildren {
  StaffCustomersRoute: typeof StaffCustomersRoute
  StaffRepairsRoute: typeof StaffRepairsRoute
}

const StaffRouteRouteChildren: StaffRouteRouteChildren = {
  StaffCustomersRoute: StaffCustomersRoute,
  StaffRepairsRoute: StaffRepairsRoute,
}

const StaffRouteRouteWithChildren = StaffRouteRoute._addFileChildren(
  StaffRouteRouteChildren,
)

interface TechnicianRouteRouteChildren {
  TechnicianDashboardRoute: typeof TechnicianDashboardRoute
  TechnicianJobsRoute: typeof TechnicianJobsRoute
  TechnicianIndexRoute: typeof TechnicianIndexRoute
}

const TechnicianRouteRouteChildren: TechnicianRouteRouteChildren = {
  TechnicianDashboardRoute: TechnicianDashboardRoute,
  TechnicianJobsRoute: TechnicianJobsRoute,
  TechnicianIndexRoute: TechnicianIndexRoute,
}

const TechnicianRouteRouteWithChildren = TechnicianRouteRoute._addFileChildren(
  TechnicianRouteRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicServicesRoute: typeof PublicServicesRoute
  PublicTrackRoute: typeof PublicTrackRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicInvoiceIdRoute: typeof PublicInvoiceIdRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicServicesRoute: PublicServicesRoute,
  PublicTrackRoute: PublicTrackRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicInvoiceIdRoute: PublicInvoiceIdRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CustomerRouteRoute: CustomerRouteRouteWithChildren,
  FinanceRouteRoute: FinanceRouteRouteWithChildren,
  InventoryRouteRoute: InventoryRouteRouteWithChildren,
  ManagementRouteRoute: ManagementRouteRouteWithChildren,
  ManagerRouteRoute: ManagerRouteRouteWithChildren,
  StaffRouteRoute: StaffRouteRouteWithChildren,
  TechnicianRouteRoute: TechnicianRouteRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiWebhooksWhatsappRoute: ApiWebhooksWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
